// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cikqdsibeuaozdneskqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpa3Fkc2liZXVhb3pkbmVza3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1OTgxMjIsImV4cCI6MjA1MTE3NDEyMn0.Hod-0s1shHBqP1WiylNPTtbvcsTkUZTUgUY8Y8-lFOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);